[package]
name = "surreal_bot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0.166"
serde_json = "1.0.100"
serenity = {default-features = false, features = ["client", "gateway", "model", 
          "rustls_backend"], version = "0.11.6"}
surrealdb = { version = "1.0.0-beta.9", features = ["kv-mem"] }
tokio = { version = "1.29.1", features = ["macros", "rt-multi-thread"] }
toml = "0.7.6"
