name: Build staging 

on:
  push:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build crate
      run: cargo build --release --verbose
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag surreal_bot:$(date +%s)
