name: Build staging 

on:
  push:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build crate
      run: cargo build --verbose
    - name: Create secrets.toml
      run: echo "DISCORD_TOKEN=\"${{secrets.STAGING_DISCORD_TOKEN}}\"">secrets.toml
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag SurrealBot:$(date +%s)
